### PR TITLE
values-bg Bulgarian localization

### PR DESCRIPTION
**Pull request by jekovcar**
[values-bg.zip](https://github.com/Jimex/DictTango-Android/files/15443844/values-bg.zip)
values-bg  contained: strings.xml & arrays.xml to the last version of DictTango 2.2.6.0

### CODE REVIEW

**Comment by Jimex** [comment]
for the arrays, please do not include those name ends with "_values", they are not supposed to be translated

**Comment by Jimex** [comment]
The strings.xml file includes items that shouldn't be translated. I've discarded your commit. Please refer to the items in values-bg-rBG and values-ru-rRU and translate them again. Thank you.

**Comment by jekovcar** [comment]
>refer to the items in values-bg-rBG and values-ru-rRU and translate them again
I don't know where are setted items, to translate them again??

**Comment by Jimex** [comment]
you can find them here:  https://github.com/Jimex/DictTango-Android/tree/main/Translation

**Pull request merged**
